### ISSUE TITLE
Emulator freeze

### ISSUE THREAD

**Issue by beerjamin** [ppaquette/gym-super-mario#12]
Fceux emulator keeps freezing seconds after the environment is deployed and it wont work after that. The provided script [nes_env.py](https://github.com/ppaquette/gym-super-mario/blob/master/ppaquette_gym_super_mario/nes_env.py) doesnt really have any impact on the emulator.
any solution would be very appreciated

**Comment by eightBEC** [comment]
Same here, after the `max_episode_steps` is reached, the emulator freezes.

**Comment by beerjamin** [comment]
what you need to do is increase the steps, what you can also do is create a list with the maps and after that you can iterate through every map with a single for loop.
