### ISSUE TITLE
Training time of openai gym is too long, what is the good way to accelerate it?

### ISSUE THREAD

**Issue by jinpengchina** [ppaquette/gym-super-mario#14]
I did some gym training what need a long time for training.

my notebook is a new macbook 12,

Such as training mario game,

what is your hardware , and how long is your time for training?

what is the good way to accelerate it?

**Comment by jinpengchina** [comment]
Typical game requires one GPU, 10 hours, 100M frames.

**Comment by robmsylvester** [comment]
This has to do entirely with your algorithm that you write for action selection. A good learner probably uses a few screenshots for a state, and probably compresses RGB to black/white. If you have experience with tensorflow and want to look at an action selection method that uses neural networks that will take a looooooooong time to learn, look at my implementation of this
