### ISSUE TITLE
Modifications required to fit latest gym version

### ISSUE THREAD

**Issue by borosdenes** [ppaquette/gym-super-mario#16]
I was trying to install your environment via `gym_pull` without success, caused by changes to `gym` itself. Please see https://github.com/openai/gym/pull/750

Reason: [gym/scoreboard](https://github.com/openai/gym/tree/master/gym/scoreboard) has changed 21 days ago, and not only `gym_pull` but also manual installation uses for example `gym.scoreboard.client` (see https://github.com/ppaquette/gym-super-mario/issues/6), which was excluded by previously mentioned merge, 21 days ago.

In order to achieve a proper environment install, I had to revert* `gym` to the state where `gym.scoreboard` was still exsisting with previous state (see following commit under `gym` [b5576dc23a5fcad0733042ab2ad440200ebb6209](https://github.com/openai/gym/commit/b5576dc23a5fcad0733042ab2ad440200ebb6209)).
*To revert, use `git checkout <commit hash> .`

After reverting, steps written by Jackiexiao (see https://github.com/ppaquette/gym-super-mario/issues/6#issuecomment-309746180) resulted in proper installation.

**Comment by borosdenes** [comment]
Update: via https://github.com/ppaquette/gym-super-mario/issues/6#issuecomment-309746180 only `gym.make('SuperMarioBros-1-1-v0')` works.

**Comment by xyzFU** [comment]
Is this the error you mean?
Error opening "Learning/venv/lib/python3.5/site-packages/gym/envs/ppaquette_gym_super_mario/roms/super-mario.nes"!
How can i change or solve this i dont understand your post exactly what file or commit is this i cant find it on my system.
Ty!

**Comment by dialogchat** [comment]
which version of gym do I need to install ??

`sudo pip install gym ==??`

**Comment by ppaquette** [comment]
Fixed in 0.0.8

**Comment by borosdenes** [comment]
I'm flabbergasted to notice that you are keep working on this repository. I'm keen to test your latest version, as soon as I can. Thank you for your work, in advance!
