### ISSUE TITLE
Install Without `gym-pull`

### ISSUE THREAD

**Issue by Kautenja** [ppaquette/gym-super-mario#19]
`gym-pull` is broken. Is there a way to install this without it?

**Comment by Kautenja** [comment]
short answer, yes. it can be imported locally to setup with gym. closing issue.

**Comment by atomikcircus3** [comment]
> 
> 
> short answer, yes. it can be imported locally to setup with gym. closing issue.

Hello, can you help me with this 'gym-super-mario' project? I want to run it up without gym-pull.

**Comment by Kautenja** [comment]
https://github.com/Kautenja/gym-super-mario-bros
