### ISSUE TITLE
Mario falls through the floor after dying?

### ISSUE THREAD

**Issue by gabegrand** [ppaquette/gym-super-mario#3]
I've noticed something strange happens when Mario dies after falling off a cliff. From the tile view, it looks like Mario gets hidden, but the underlying object persists for a few seconds and keeps falling. I'm concerned that this behavior may be interfering with reinforcement learning, since the agent continues to take actions and receive rewards even after Mario dies. What do you think?

![mario2](https://cloud.githubusercontent.com/assets/10052880/20545671/7553b60e-b0de-11e6-9e7d-780ecfd4a2eb.gif)

**Comment by ppaquette** [comment]
Good catch. I was only using the game y position, but the value loops around if Mario is above or below the viewport.

I've implemented a fix (master branch) that doesn't display the red tile if Mario is above or below the viewport, and that returns is_dead() as soon as Mario falls below the viewport.

**Comment by gabegrand** [comment]
Fantastic. The fix for this works great. One question: what exactly is it that returns `is_dead` when Mario dies? Is `is_dead()` a method in the environment?

**Comment by ppaquette** [comment]
Its a function in fceux (lua) that detects when the episode is done, so the `step` function can returned `finished = true`

-- https://github.com/ppaquette/gym-super-mario/blob/master/ppaquette_gym_super_mario/lua/super-mario-bros.lua#L282

**Comment by gabegrand** [comment]
When the step function returns `finished = true`, is there some way to distinguish whether the cause of `finished` is because Mario died, or because the level was completed? I'd like to penalize dying in the reward function.

**Comment by ppaquette** [comment]
Pushed a patch. Check the value of the `life` key in the info dict when `step` returns `is_finished = true`.

- `life = 3` will be returned if player is still alive (so level is completed successfully)
- `life = 0` will be returned if player is dead before completing the level.
